export const QUOTE_STYLE_DEFAULTS = {
  company_name: 'iProject',
  primary_color: '#004E9A',
  secondary_color: '#DCE8F5',
  company_address: '',
  company_phone: '',
  company_email: '',
  header_text: '',
  footer_text: '',
  font_family: 'sans',
  title_alignment: 'center',
  info_alignment: 'center',
  header_alignment: 'center',
  footer_alignment: 'center',
  language: 'zh',
  logo_position: 'center',
  quote_date: '',
  logo: null,
  field_visibility: {
    quote_no: 1,
    quote_date: 1,
    order_no: 1,
    project_name: 1,
    end_customer: 1,
    contract_customer: 1,
    contact_info: 1,
    material_no: 1,
    description: 1,
    type: 1,
    price_source: 1,
    unit_price: 1,
    qty: 1,
    line_amount: 1
  },
  labels: {
    quote_title: '报价单',
    quote_date: '报价日期',
    quote_no: '报价单编号',
    order_no: '销售机会编号',
    project_name: '项目名称',
    end_customer: '最终客户',
    contract_customer: '合同客户',
    detail_title: '报价明细',
    total: '合计（未税）',
    material_no: '物料号',
    description: '描述',
    type: '类型',
    price_source: '价格来源',
    unit_price: '单价',
    qty: '数量',
    line_amount: '行金额'
  },
  labels_en: {
    quote_title: 'Quotation',
    quote_date: 'Quotation Date',
    quote_no: 'Quotation No.',
    order_no: 'Order No.',
    project_name: 'Project Name',
    end_customer: 'End Customer',
    contract_customer: 'Contract Customer',
    detail_title: 'Quotation Details',
    total: 'Total (Excl. VAT)',
    material_no: 'Material No.',
    description: 'Description',
    type: 'Type',
    price_source: 'Price Source',
    unit_price: 'Unit Price',
    qty: 'Qty',
    line_amount: 'Line Amount'
  }
};
